
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbdeyaptiwwbmkeulxbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiZGV5YXB0aXd3Ym1rZXVseGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MzU0NTIsImV4cCI6MjA1NjMxMTQ1Mn0.mR46FTcPTVFbM31bsIpRYy_EDW_Q7ypa1NQO_Xj0Fjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
